/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;

import org.example.views.Home;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {

  @Override
  public void start(Stage stage) {

    Home home = new Home();
    home.homePage(stage);
  }

  public static void main(String[] args) {
    launch();
  }
}
